# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d64afa368a3f2747e26623d153a115b681e6a90369918ee9ef184d89e8384aaf45ef6a05699a482bbb1f8724af3a885353f85d2cf2538251e81ab0ca62b355d0

test:
  secret_key_base: 4834bd365ba316d432c6072c60263724f62a7bb32d683a119d11e05bb25e1db49502c99dbb12443f1c636d38015aa5f1c6c95fd4195449747858a49cf312c4e9

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
